<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Course Already Exists with this Course code.' => 'Curso ya existe el con este código Curso.',
    'Section Already Exists of this Batch.' => 'Sección ya existe el de este lote.',
    '--- Select Course ---' => '--- Seleccionar Cursos ---',
    'ADD' => 'AGREGAR',
    'Active' => 'Activo',
    'Add' => 'AGREGAR',
    'Add Batch' => 'Agregar Lote',
    'Add Course' => 'Agregar Curso',
    'Add Section' => 'Agregar Sección',
    'Are you sure you want to delete this item?' => '¿Desea eliminar el ítem?',
    'Back' => 'Atrás',
    'Batch' => 'Lote',
    'Batch Alias' => 'Alias de Lote',
    'Batch Course' => 'Lote del Curso',
    'Batch ID' => 'ID Lote',
    'Batch Name' => 'Nombre del Lote',
    'Batches' => 'Lotes',
    'Cancel' => 'Cancelar',
    'Course' => 'Curso',
    'Course Alias' => 'Alias del Curso',
    'Course Code' => 'Código del Curso',
    'Course ID' => 'ID Curso',
    'Course Management' => 'Administración de Cursos',
    'Course Name' => 'Nombre de Curso',
    'Create' => 'Crear',
    'Create New' => 'Crear Nuevo',
    'Create Section' => 'Crear Sección ',
    'Created At' => 'Creado En',
    'Created By' => 'Creado Por',
    'Delete' => 'Borrar',
    'EXCEL' => 'EXCEL',
    'Edit Batch Details' => 'Editar Detalles de Lotes',
    'Edit Course Details' => 'Editar Detalles de Curso',
    'Edit Section Details' => 'Editar Detalles de Sección',
    'End Date' => 'Fecha Final',
    'Inactive' => 'Inactivo',
    'Initial Batch' => 'lote inicial',
    'Initial Section' => 'Sección inicial',
    'Intake' => 'Cupo',
    'Manage Batches' => 'Administrar Lotes',
    'Manage Course' => 'Administrar Curso',
    'Manage Course Modules' => 'Gestionar módulos de Cursos',
    'Manage Courses' => 'Administrar Cursos',
    'Manage Current Active Course' => 'Administrar Cursos Activos Actualmente',
    'Manage Section' => 'Administrar Secciones',
    'Manage Sections' => 'Administrar Secciones',
    'No results found.' => 'No se han encontrado resultados.',
    'PDF' => 'PDF',
    'Section' => 'Sección',
    'Section Batch' => 'Lote de Sección',
    'Section ID' => 'ID Sección',
    'Section Name' => 'Nombre de Sección',
    'Start Date' => 'Fecha de Inicio',
    'Status' => 'Estado',
    'Students' => 'Estudiantes',
    'Update' => 'Actualización',
    'Update Batch' => 'Actualizar Lotes',
    'Update Batches: ' => 'Actualizar Lotes: ',
    'Update Course' => 'Actualizar Curso',
    'Update Courses: ' => 'Actualizar Curso: ',
    'Update Section' => 'Actualizar Sección',
    'Update Section: ' => 'Actualizar Sección: ',
    'Updated At' => 'Actualizado a las',
    'Updated By' => 'Actualizado por el',
    'View Batch' => 'Ver Lote',
    'View Batch Details' => 'Ver Detalle de Lotes',
    'View Course' => 'Ver Curso',
    'View Course Details' => 'Ver Detalles del Curso',
    'View Section' => 'Ver Sección',
    'View Section Details' => 'Ver Detalles de Sección',
];
