<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '--- Select Type ---' => '--- Seleccionar Tipo ---',
    'ADD' => 'AGREGAR',
    'Active' => 'Activo',
    'Add Event' => 'Agregar Evento',
    'Add Message of Day' => 'Agregar Mensaje del Día',
    'Add Notice' => 'Agregar Noticia',
    'All Day' => 'Todo el Día ',
    'Are you sure you want to delete this item?' => '¿Desea eliminar el ítem?',
    'Back' => 'Atrás',
    'Cancel' => 'Cancelar',
    'Create' => 'Crear',
    'Create Events' => 'Crear Evento',
    'Create New' => 'Crear Nuevo',
    'Created At' => 'Creado En',
    'Created By' => 'Creado Por',
    'Dashboard' => 'Dashboard',
    'Dashboard Modules' => 'Módulos del Dashboard',
    'Date' => 'Fecha',
    'Deactive' => 'Desactivar',
    'Delete' => 'Borrar',
    'Description' => 'Descripción',
    'Detail' => 'Detalle',
    'Details' => 'Detalles',
    'EXCEL' => 'EXCEL',
    'Employee' => 'Empleado',
    'End Date' => 'Fecha Final',
    'Enter Description' => 'Introduzca Descripción',
    'Enter Message Details' => 'Introduzca Detalle del Mensaje',
    'Enter Title' => 'Introduzca Titulo',
    'Event ID' => 'ID Evento',
    'Event Schedule' => 'Calendario de Eventos',
    'Event Type' => 'Tipo de Evento',
    'Events' => 'Eventos',
    'General' => 'General',
    'Holiday' => 'Vacación',
    'Important Notice' => 'Noticia Importante',
    'Is Status' => 'Estado',
    'Manage Event Schedule' => 'Administrar Calendario de Eventos',
    'Manage Events' => 'Administrar Eventos',
    'Manage Student/Employee Dashboard Notice' => 'Administrar Dashboard de Aviso de Estudiante/Empleado',
    'Manage Users Dashboard' => 'Administrar Dashboard de Usuario',
    'Massage Of The Day' => 'Mensaje Del Día',
    'Meeting' => 'Lista de Mensajes del Día',
    'Message of Day List' => 'Lista de Mensajes del Día',
    'Messages' => 'Mensajes',
    'Msg Of Day ID' => 'ID Mensaje del Día',
    'Notice' => 'Noticia',
    'Notice File' => 'Archivo de Noticia',
    'Notice ID' => 'ID Noticia',
    'Notice List' => 'Lista de Noticias',
    'PDF' => 'PDF',
    'Remove' => 'Remover',
    'Remove/Delete Event' => 'Remover/Eliminar Evento',
    'Select Date' => 'Seleccionar Fecha',
    'Start Date' => 'Fecha de Inicio',
    'Status' => 'Estado',
    'Student' => 'Estudiante',
    'Title' => 'Titulo',
    'Update' => 'Actualización',
    'Update Event' => 'Actualizar Evento',
    'Update Events: ' => 'Actualizar Evento: ',
    'Update Message of Day' => 'Actualizar Mensaje del Día',
    'Update Message of Day: ' => 'Actualizar Mensaje del Día: ',
    'Update Notice' => 'Actualizar de Noticia',
    'Update Notice: ' => 'Actualizar de Noticia: ',
    'Updated At' => 'Actualizado a las',
    'Updated By' => 'Actualizado por el',
    'Url' => 'Url',
    'User Type' => 'Tipo de Usuario',
    'View Message of Days' => 'Ver Mensajes del Día',
    'View Notice' => 'Ver Noticia',
];
