<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '--- Select Department ---' => '--- Seleccionar Departamento ---',
    '--- Select Designation ---' => '--- Seleccionar Designación ---',
    'Active Employee' => 'Empleado Activo',
    'Active Students' => 'Estudiante Activo',
    'Address' => 'Dirección',
    'Admission Date' => 'Fecha de Admisión',
    'Attendence Card' => 'Tarjeta de Asistencia',
    'Back' => 'Atrás',
    'Bank Account No' => 'N° de Cuenta Bancaria',
    'Batch' => 'Lote',
    'Batch Name' => 'Nombre del Lote',
    'Birth Date' => 'Fecha de cumpleaños',
    'Birth Place' => 'Lugar de Nacimiento',
    'Blood' => 'Sangre',
    'Blood Group' => 'Grupo Sanguíneo',
    'Category' => 'Categoría',
    'Category Name' => 'Nombre de Categoría',
    'Category Wise Student' => 'Categoría de Estudiante',
    'Check All' => 'Seleccionar Todos',
    'City' => 'Ciudad',
    'Course' => 'Curso',
    'Course Wise Student Status' => 'Estado Actual de Cursos del Estudiante',
    'Date' => 'Fecha',
    'Deactive Employee' => 'Empleado Inactivo',
    'Deactive Students' => 'Estudiante Inactivo',
    'Department' => 'Departamento',
    'Department Wise Joining Average' => 'Promedios actuales de Ingreso a los Departamentos',
    'Designation' => 'Denominación',
    'Email ID' => 'ID de Correo Electrónico',
    'Email Id' => 'ID de Correo Electrónico',
    'Email-ID' => 'ID de Correo Electrónico',
    'Employee Info Report' => 'Reporte de Información de Empleados',
    'Employee List' => 'Lista de Empleado',
    'Employee No' => 'N° Empleado',
    'Excel' => 'Excel',
    'First Name' => 'Nombre',
    'Gender' => 'Sexo',
    'Gender Wise Employee' => 'Sexo Actual de Empleados',
    'Gender Wise Student' => 'Sexo Actual de Estudiantes',
    'Generate' => 'Generar',
    'Group' => 'Grupo',
    'Guardian' => 'Tutor',
    'Guardian Mobile' => 'Celular del Tutor',
    'Guardian No' => 'N° Tutor',
    'International' => 'Internacional',
    'International Address' => 'Dirección Internacional',
    'Joining' => 'Unirse',
    'Joining Date' => 'Día de Ingreso',
    'Languages Known' => 'Idiomas Conocidos',
    'Last Name' => 'Apellido',
    'Local' => 'Local',
    'Local Address' => 'Dirección Local',
    'Login History' => 'Historial de Inicio de Sesión',
    'Marital Status' => 'Estado Civil',
    'Middle Name' => 'Segundo Nombre',
    'Mobile No' => 'N° Móvil',
    'More Info' => 'Más información',
    'Mother Name' => 'Nombre de Madre',
    'No' => 'No',
    'No Record Found For This Criteria.' => 'No se encontraron registros para el criterio de búsqueda.',
    'No Record To Display' => 'No existen registros para mostrar',
    'Not Set' => 'No Configurado',
    'PDF' => 'PDF',
    'Please select atleast one checkbox' => 'Favor seleccione por lo menos un elemento',
    'Reference' => 'Referencia',
    'Religion' => 'Religión',
    'Report Center' => 'Centro de Reporte',
    'Reports' => 'Reportes',
    'SI No.' => 'N° Serie',
    'Section' => 'Sección',
    'Section Name' => 'Nombre de Sección',
    'Select Criteria' => 'Seleccione Criterios',
    'Sr.No' => 'N° Serie',
    'Student Count' => 'Cantidad de Estudiantes',
    'Student Info Report' => 'Reporte de Información de Estudiante',
    'Student No' => 'N° de Estudiante',
    'Student Report' => 'Reporte de Estudiante',
    'Students List' => 'Lista de Estudiantes ',
    'Total Employee' => 'Total de Empleados',
    'Year Wise Joining Employees' => 'Año de Ingreso Actual de Empleados',
];
