<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Course Already Exists with this Course code.' => 'Cours existe déjà avec ce code de cours.',
    'Section Already Exists of this Batch.' => 'Section existe déjà de ce lot.',
    '--- Select Course ---' => '--- Choisir cours ---',
    'ADD' => 'Ajouter',
    'Active' => 'opérationnel',
    'Add' => 'Ajouter',
    'Add Batch' => 'Ajouter collection',
    'Add Course' => 'Nouveau cours',
    'Add Section' => 'Nouvelle section',
    'Are you sure you want to delete this item?' => 'Supprimer cet outil ?',
    'Back' => 'Retourner',
    'Batch' => 'Collection',
    'Batch Alias' => 'Surnom du cours',
    'Batch Course' => 'Collections des cours',
    'Batch ID' => 'Identifiant du lot',
    'Batch Name' => 'Nom de la collection',
    'Batches' => 'Lots',
    'Cancel' => 'Décommander',
    'Course' => 'Cours',
    'Course Alias' => 'Cours alias',
    'Course Code' => 'Code du cours',
    'Course ID' => 'Identifiant du cours',
    'Course Management' => 'Management des cours',
    'Course Name' => 'Cours',
    'Create' => 'Nouveau',
    'Create New' => 'Ajouter nouveau',
    'Create Section' => 'Ajouter section',
    'Created At' => 'Créé a',
    'Created By' => 'Fait par',
    'Delete' => 'Supprimer',
    'EXCEL' => 'Excel',
    'Edit Batch Details' => 'Editer détails des collections',
    'Edit Course Details' => 'Editer les détails des cours',
    'Edit Section Details' => 'Editer les détails de la section',
    'End Date' => 'Fin',
    'Inactive' => 'Inopérant',
    'Initial Batch' => 'Collection initiale',
    'Initial Section' => 'section initiale',
    'Intake' => 'Acceptation',
    'Manage Batches' => 'Gestion des lots',
    'Manage Course' => 'Gestion de la leçon',
    'Manage Course Modules' => 'Gérer modules des cours',
    'Manage Courses' => 'Gestion des cours',
    'Manage Current Active Course' => 'Gestion de l’actuel cours actif',
    'Manage Section' => 'Gestion de la section',
    'Manage Sections' => 'Gestion des sections',
    'No results found.' => 'Pas de résultat',
    'PDF' => 'PDF',
    'Section' => 'Section',
    'Section Batch' => 'Lot de la section',
    'Section ID' => 'Identifiant de la section',
    'Section Name' => 'Nom de catégorie',
    'Start Date' => 'Date début',
    'Status' => 'Statut',
    'Students' => 'Elèves',
    'Update' => 'Mettre à jour',
    'Update Batch' => 'Mettre à jour la collection',
    'Update Batches: ' => 'Mettre à jour les collections: ',
    'Update Course' => 'Mettre cours à jour',
    'Update Courses: ' => 'Mettre à jour les cours: ',
    'Update Section' => 'Mettre à jour la section',
    'Update Section: ' => 'Mettre à jour la section: ',
    'Updated At' => 'Actualiser a',
    'Updated By' => 'Mis à jour par',
    'View Batch' => 'Visualiser la collection',
    'View Batch Details' => 'Visualiser les détails du lot',
    'View Course' => 'Visualiser le cours',
    'View Course Details' => 'Visualiser les détails du cours',
    'View Section' => 'Visualiser la section',
    'View Section Details' => 'Visualiser les détails du section',
];
