<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add Event' => 'Nouvel évènement',
    'Update Event' => 'Mettre à jour l’évènement',
    '--- Select Type ---' => '--- Choisir type ---',
    'ADD' => 'Ajouter',
    'Active' => 'opérationnel',
    'Add Message of Day' => 'Ajouter le message du jour',
    'Add Notice' => 'Ajouter notification',
    'All Day' => 'Tous les jours',
    'Are you sure you want to delete this item?' => 'Supprimer cet outil ?',
    'Back' => 'Retourner',
    'Cancel' => 'Décommander',
    'Create' => 'Nouveau',
    'Create Events' => 'Ajouter évènements',
    'Create New' => 'Ajouter nouveau',
    'Created At' => 'Créé a',
    'Created By' => 'Fait par',
    'Dashboard' => 'Interface',
    'Dashboard Modules' => 'Tableau de bord des modules',
    'Date' => 'Date',
    'Deactive' => 'Décommander',
    'Delete' => 'Supprimer',
    'Description' => 'Explication',
    'Detail' => 'Détail',
    'Details' => 'Spécifications',
    'EXCEL' => 'Excel',
    'Employee' => 'Travailleur',
    'End Date' => 'Fin',
    'Enter Description' => 'Tapez description',
    'Enter Message Details' => 'Ecrire les détails du message',
    'Enter Title' => 'Tapez/saisissez le titre',
    'Event ID' => 'Identifiant de l’évènement',
    'Event Schedule' => 'Horaire de l’évènement',
    'Event Type' => 'Genre d’évènement',
    'Events' => 'Evènements',
    'General' => 'général',
    'Holiday' => 'Congés',
    'Important Notice' => 'Message important',
    'Is Status' => 'Statut IS',
    'Manage Event Schedule' => 'Gérer calendriers des évènements',
    'Manage Events' => 'Gestion des évènements',
    'Manage Student/Employee Dashboard Notice' => 'Gérer interface d’annonce pour étudiants/employés',
    'Manage Users Dashboard' => 'Tableau de bord des managers',
    'Massage Of The Day' => 'Mot du jour',
    'Meeting' => 'Rencontre',
    'Message of Day List' => 'Liste messages journaliers',
    'Messages' => 'Annonces',
    'Msg Of Day ID' => 'Titre du message du jour',
    'Notice' => 'Message',
    'Notice File' => 'Fichier de notifications',
    'Notice ID' => 'Identifiant de la notification ',
    'Notice List' => 'Liste de communiques',
    'PDF' => 'PDF',
    'Remove' => 'Enlever',
    'Remove/Delete Event' => 'Enlevez/effacer évènement',
    'Select Date' => 'Choisir date',
    'Start Date' => 'Date début',
    'Status' => 'Statut',
    'Student' => 'Elève',
    'Title' => 'Titre',
    'Update' => 'Mettre à jour',
    'Update Events: ' => 'Mettre à jour les évènements: ',
    'Update Message of Day' => 'Mettre à jour message du jour',
    'Update Message of Day: ' => 'Mettre à jour message du jour: ',
    'Update Notice' => 'Mettre annonce à jour',
    'Update Notice: ' => 'Mettre annonce à jour: ',
    'Updated At' => 'Actualiser a',
    'Updated By' => 'Mis à jour par',
    'Url' => 'Adresse web',
    'User Type' => 'Catégorie utilisateur',
    'View Message of Days' => 'Voir annonces du jour',
    'View Notice' => 'Voir annonce',
];
