<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Reports Center' => '@@@@',
    '--- Select Department ---' => '--- Choisir département ---',
    '--- Select Designation ---' => '--- Choisir désignation ---',
    'Active Employee' => 'Employé actif ',
    'Active Students' => 'Elèves actifs',
    'Address' => 'Adresse',
    'Admission Date' => 'Date d’acceptation',
    'Attendence Card' => 'Carte de membre',
    'Back' => 'Retourner',
    'Bank Account No' => 'Numéro de compte',
    'Batch' => 'Collection',
    'Batch Name' => 'Nom de la collection',
    'Birth Date' => 'Ne le...',
    'Birth Place' => 'Né a',
    'Blood' => 'Sang',
    'Blood Group' => 'Classification sanguine',
    'Category' => 'Catégorie',
    'Category Name' => 'Nom de la catégorie',
    'Category Wise Student' => 'Etudiants selon catégories',
    'Check All' => 'Tout vérifier',
    'City' => 'Ville',
    'Course' => 'Cours',
    'Course Wise Student Status' => 'Statut des étudiants par rapport aux cours',
    'Date' => 'Date',
    'Deactive Employee' => 'Travailleur non-actif',
    'Deactive Students' => 'Elèves non-actifs',
    'Department' => 'Division administrative',
    'Department Wise Joining Average' => 'Moyenne d’arrivées dans les départements',
    'Designation' => 'Appellation',
    'Email ID' => 'Email identifiant',
    'Email Id' => 'Email identifiant',
    'Email-ID' => 'Email identifiant',
    'Employee Info Report' => 'Informations sur le travailleur',
    'Employee List' => 'Liste des travailleurs',
    'Employee No' => 'Numéro du travailleur',
    'Excel' => 'Excel',
    'First Name' => 'Prénom',
    'Gender' => 'Genre',
    'Gender Wise Employee' => 'Employés selon genres',
    'Gender Wise Student' => 'Etudiants par catégories du genre',
    'Generate' => 'Générer',
    'Group' => 'Groupe',
    'Guardian' => 'Gardien',
    'Guardian Mobile' => 'Numéro du gardien',
    'Guardian No' => 'Numéro du tuteur',
    'International' => 'International',
    'International Address' => 'Domicile internationale',
    'Joining' => 'Rejoignant',
    'Joining Date' => 'Arrivé le...',
    'Languages Known' => 'Langues parlées',
    'Last Name' => 'Post nom',
    'Local' => 'Local',
    'Local Address' => 'Adresse',
    'Login History' => 'Historique de connexion',
    'Marital Status' => 'Situation publique',
    'Middle Name' => 'nom',
    'Mobile No' => 'Numéro de téléphone',
    'More Info' => 'Plus de détails',
    'Mother Name' => 'Nom de la maman',
    'No' => 'Non',
    'No Record Found For This Criteria.' => 'Aucune donnée pour ce critère.',
    'No Record To Display' => 'Aucune information',
    'Not Set' => 'Non paramétré',
    'PDF' => 'PDF',
    'Please select atleast one checkbox' => 'Choisir au moins une case',
    'Reference' => 'Reference',
    'Religion' => 'Confession religieuse',
    'Report Center' => 'Centre pour rapports',
    'Reports' => 'Comptes rendus',
    'SI No.' => 'SI No.',
    'Section' => 'Classe',
    'Section Name' => 'Nom de la section',
    'Select Criteria' => 'Choisir critère',
    'Sr.No' => 'Sr. No',
    'Student Count' => 'Nombre d’élèves',
    'Student Info Report' => 'Rapport informations de l’élève',
    'Student No' => 'Numéro d’élève',
    'Student Report' => 'rapport de étudiant',
    'Students List' => 'Liste d’élèves',
    'Total Employee' => 'Nombre total des employés',
    'Year Wise Joining Employees' => 'Travailleurs selon année d’arrivée',
];
