<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Batch' => '',
    'Course' => '',
    'Section' => '',
    '--- Select Course ---' => '--- पाठ्यक्रम चुनिए ---',
    'ADD' => 'ऐड किजीऐ',
    'Active' => 'सक्रिय',
    'Add' => 'ऐड किजीऐ',
    'Add Batch' => 'ऐड बैच',
    'Add Course' => 'ऐड पाठ्यक्रम',
    'Add Section' => 'ऐड सेक्शन',
    'Are you sure you want to delete this item?' => 'आप इस रिकॉर्ड को नष्ट करना चाहते हैं आप सुनिश्चित हैं?',
    'Back' => 'वापस जाएँ',
    'Batch Alias' => 'बैच का उपनाम',
    'Batch Course' => 'पाठ्यक्रम',
    'Batch ID' => 'बैच ID',
    'Batch Name' => 'बैच का नाम',
    'Batches' => 'बैच',
    'Cancel' => 'रद्द करें',
    'Course Alias' => 'पाठ्यक्रम का उपनाम',
    'Course Code' => 'पाठ्यक्रम कोड',
    'Course ID' => 'पाठ्यक्रम ID',
    'Course Management' => 'कोर्स मैनेजमेंट',
    'Course Name' => 'पाठ्यक्रम का नाम',
    'Create' => 'बनाएं',
    'Create New' => 'नया बनाएँ',
    'Create Section' => 'सेक्शन बनाएँ',
    'Created At' => 'बनाने का समय',
    'Created By' => 'यूजर बनाइये',
    'Delete' => 'मिटायें',
    'EXCEL' => 'एक्सेल',
    'Edit Batch Details' => 'बैच डिटेल्स संपादित करें',
    'Edit Course Details' => 'पाठ्यक्रम डिटेल्स संपादित करें',
    'Edit Section Details' => 'सेक्शन डिटेल्स संपादित करें',
    'End Date' => 'समाप्ति तारीख',
    'Inactive' => 'निष्क्रिय',
    'Intake' => 'क्षमता',
    'Manage Batches' => 'बैच मेनेज करें',
    'Manage Course' => 'पाठ्यक्रम  मेनेज करें',
    'Manage Course Modules' => 'पाठ्यक्रम मॉड्यूल मेनेज करें',
    'Manage Courses' => 'पाठ्यक्रम  मेनेज करें',
    'Manage Current Active Course' => 'वर्तमान सक्रिय कोर्स मेनेज करें',
    'Manage Section' => 'सेक्शन मेनेज करें',
    'Manage Sections' => 'सेक्शन मेनेज करें',
    'No results found.' => 'कोई परिणाम नहीं मिला।',
    'PDF' => 'पीडीएफ',
    'Section Batch' => 'पाठ्यक्रम',
    'Section ID' => 'सेक्शन ID',
    'Section Name' => 'सेक्शन का नाम',
    'Start Date' => 'आरंभ तारीख़',
    'Status' => 'स्थिति',
    'Students' => 'छात्र',
    'Update' => 'अपडेट करें',
    'Update Batch' => 'बैच अपडेट करें',
    'Update Batches: ' => 'बैच अपडेट करें : ',
    'Update Course' => 'पाठ्यक्रम अपडेट करें',
    'Update Courses: ' => 'पाठ्यक्रम अपडेट करें : ',
    'Update Section' => 'सेक्शन अपडेट करें',
    'Update Section: ' => 'सेक्शन अपडेट करें : ',
    'Updated At' => 'अपडेट का समय',
    'Updated By' => 'द्वारा अपडेट कीया गया',
    'View Batch' => 'बैच देखें',
    'View Batch Details' => 'बैच डिटेल्स देखें',
    'View Course' => 'पाठ्यक्रम देखें',
    'View Course Details' => 'पाठ्यक्रम डिटेल्स देखें',
    'View Section' => 'सेक्शन देखें',
    'View Section Details' => 'सेक्शन डिटेल्स देखें',
];
