<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add Event' => 'इवेन्ट जोड़ें',
    'Update Event' => 'इवेन्ट अपडेट करें ',
    'Url' => '',
    '--- Select Type ---' => '--- प्रकार चुनिए ---',
    'ADD' => 'नया जोड़ें',
    'Active' => 'सक्रिय',
    'Add Message of Day' => 'आज का संदेश जोड़ें',
    'Add Notice' => 'नोटिस जोड़ें',
    'All Day' => 'सभी दिन',
    'Are you sure you want to delete this item?' => 'आप इस रिकॉर्ड को नष्ट करना चाहते हैं आप सुनिश्चित हैं?',
    'Back' => 'वापस जाएँ',
    'Cancel' => 'रद्द करें',
    'Create' => 'बनाएं',
    'Create Events' => 'इवेन्ट बनाएं',
    'Create New' => 'नया बनाएँ',
    'Created At' => 'बनाने का समय',
    'Created By' => 'द्वारा बनाया गया',
    'Dashboard' => 'डैशबोर्ड',
    'Dashboard Modules' => 'डैशबोर्ड मॉड्यूल',
    'Date' => 'तारीख',
    'Deactive' => 'निष्क्रिय',
    'Delete' => 'मिटायें',
    'Description' => 'विवरण',
    'Detail' => 'विवरण',
    'Details' => 'विवरण',
    'EXCEL' => 'एक्सेल',
    'Employee' => 'कर्मचारी',
    'End Date' => 'समाप्ति  तारीख',
    'Enter Description' => 'विवरण दर्ज करें',
    'Enter Message Details' => 'संदेश की जानकारी दर्ज करें',
    'Enter Title' => 'शीर्षक दर्ज करें',
    'Event ID' => 'इवेन्ट आईडी',
    'Event Schedule' => 'इवेन्ट शेड्यूल',
    'Event Type' => 'इवेन्ट का प्रकार',
    'Events' => 'इवेन्टस',
    'General' => 'जनरल',
    'Holiday' => 'छुट्टी ',
    'Important Notice' => 'महत्वपूर्ण नोटिस',
    'Is Status' => 'स्थिति?',
    'Manage Event Schedule' => 'इवेन्ट शेड्यूल मेनेज करें',
    'Manage Events' => 'इवेन्टस मेनेज करें',
    'Manage Student/Employee Dashboard Notice' => 'छात्र/कर्मचारी डैशबोर्ड नोटिस मेनेज करें',
    'Manage Users Dashboard' => 'यूजर डैशबोर्ड मेनेज करें',
    'Massage Of The Day' => 'आज का संदेश',
    'Meeting' => 'बैठक',
    'Message of Day List' => 'आज का संदेश',
    'Messages' => 'संदेशे',
    'Msg Of Day ID' => 'आज का संदेश आईडी',
    'Notice' => 'नोटिस',
    'Notice File' => 'नोटिस फ़ाइल',
    'Notice ID' => 'नोटिस आईडी',
    'Notice List' => 'नोटिस की सूची',
    'PDF' => 'पीडीएफ',
    'Remove' => 'हटाये',
    'Remove/Delete Event' => 'इवेन्ट हटाएं/निकालें',
    'Select Date' => 'तारीख़ चुनिए',
    'Start Date' => 'आरंभ तारीख़',
    'Status' => 'स्थिति',
    'Student' => 'छात्र',
    'Title' => 'शीर्षक',
    'Update' => 'अपडेट करें',
    'Update Events: ' => 'इवेन्टस अपडेट करें : ',
    'Update Message of Day' => 'आज का संदेश अपडेट करें',
    'Update Message of Day: ' => 'आज का संदेश अपडेट करें : ',
    'Update Notice' => 'नोटिस अपडेट करें',
    'Update Notice: ' => 'नोटिस अपडेट करें : ',
    'Updated At' => 'अपडेट का समय',
    'Updated By' => 'द्वारा अपडेट कीया गया',
    'User Type' => 'यूजर का प्रकार',
    'View Message of Days' => 'आज का संदेश देखें',
    'View Notice' => 'नोटिस देखें',
];
