<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Reports Center' => '@@@@',
    '--- Select Department ---' => '--- विभाग चुनिए ---',
    '--- Select Designation ---' => '--- पद चुनिए ---',
    'Active Employee' => 'सक्रिय कर्मचारी',
    'Active Students' => 'सक्रिय छात्र',
    'Address' => 'पता',
    'Admission Date' => 'एडमिशन की तारीख',
    'Attendence Card' => 'उपस्थिति कार्ड',
    'Back' => 'वापस जाएँ',
    'Bank Account No' => 'बैंक खाता नं.',
    'Batch' => 'बैच',
    'Batch Name' => 'बैच का नाम',
    'Birth Date' => 'जन्म तारीख',
    'Birth Place' => 'जन्म स्थान',
    'Blood' => 'ब्लड',
    'Blood Group' => 'ब्लड ग्रुप',
    'Category' => 'श्रेणी',
    'Category Name' => 'श्रेणी का नाम',
    'Category Wise Student' => 'श्रेणीवार छात्र',
    'Check All' => 'सभी चेक करें',
    'City' => 'शहर',
    'Course' => 'पाठ्यक्रम',
    'Course Wise Student Status' => 'पाठ्यक्रमवार छात्र',
    'Date' => 'तारीख',
    'Deactive Employee' => 'निष्क्रिय कर्मचारी',
    'Deactive Students' => 'निष्क्रिय छात्र',
    'Department' => 'विभाग',
    'Department Wise Joining Average' => 'विभागवार शामिल होने की औसत',
    'Designation' => 'पद',
    'Email ID' => 'ईमेल आईडी',
    'Email Id' => 'ईमेल आईडी',
    'Email-ID' => 'ईमेल -आईडी',
    'Employee Info Report' => 'कर्मचारी जानकारी रिपोर्ट',
    'Employee List' => 'कर्मचारी सूची',
    'Employee No' => 'कर्मचारी नं.',
    'Excel' => 'एक्सेल',
    'First Name' => 'पहला नाम',
    'Gender' => 'जाति',
    'Gender Wise Employee' => 'जातिवार कर्मचारी',
    'Gender Wise Student' => 'जातिवार छात्र',
    'Generate' => 'बनाएं',
    'Group' => 'समूह',
    'Guardian' => 'अभिभावक',
    'Guardian Mobile' => 'अभिभावक मोबाइल नं.',
    'Guardian No' => 'अभिभावक नं.',
    'International' => 'अंतरराष्ट्रीय',
    'International Address' => 'अंतरराष्ट्रीय पता',
    'Joining' => 'शामिल',
    'Joining Date' => 'शामिल होने की तारीख',
    'Languages Known' => 'ज्ञात भाषाएँ',
    'Last Name' => 'अंतिम नाम',
    'Local' => 'स्थानीय',
    'Local Address' => 'स्थानीय पता',
    'Login History' => 'लॉगिन इतिहास',
    'Marital Status' => 'वैवाहिक स्थिति',
    'Middle Name' => 'मध्य नाम',
    'Mobile No' => 'मोबाइल नं.',
    'More Info' => 'अधिक जानकारी',
    'Mother Name' => 'माता का नाम',
    'No' => 'नहीं',
    'No Record Found For This Criteria.' => 'इस मापदंड के लिए कोई रिकॉर्ड नहीं मिला है।',
    'No Record To Display' => 'कोई रिकॉर्ड प्रदर्शन करने के लिए नहीं है।',
    'Not Set' => 'सेट नहीं है',
    'PDF' => 'पीडीएफ',
    'Please select atleast one checkbox' => 'कृपया न्यूनतम एक चेकबॉक्स का चयन करें।',
    'Reference' => 'रेफरेंस',
    'Religion' => 'धर्म',
    'Report Center' => 'रिपोर्ट केंद्र',
    'Reports' => 'रिपोर्ट्स',
    'SI No.' => 'सीरियल नं.',
    'Section' => 'सेक्शन',
    'Section Name' => 'सेक्शन  का नाम',
    'Select Criteria' => 'मापदंड चुनिए',
    'Sr.No' => 'सीरियल नं.',
    'Student Count' => 'छात्र संख्या',
    'Student Info Report' => 'छात्र जानकारी रिपोर्ट',
    'Student No' => 'छात्र नं.',
    'Student Report' => 'छात्र की रिपोर्ट',
    'Students List' => 'छात्र की सूची',
    'Total Employee' => 'कुल कर्मचारी',
    'Year Wise Joining Employees' => 'वर्षवार कर्मचारियों शामिल होने की औसत',
];
