<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add Sub Head' => 'उप प्रधान ऐड करे',
    'Are you sure you want to delete this item?' => 'आप इस रिकॉर्ड को नष्ट करना चाहते हैं आप सुनिश्चित हैं?',
    'Delete' => 'मिटायें',
    'Update' => 'अपडेट करें',
    'View' => 'देखें',
];
