<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '--- Select Course ---' => '',
    'ADD' => '',
    'Active' => '',
    'Add' => '',
    'Add Batch' => '',
    'Add Course' => '',
    'Add Section' => '',
    'Are you sure you want to delete this item?' => '',
    'Back' => '',
    'Batch' => '',
    'Batch Alias' => '',
    'Batch Course' => '',
    'Batch ID' => '',
    'Batch Name' => '',
    'Batches' => '',
    'Cancel' => '',
    'Course' => '',
    'Course Alias' => '',
    'Course Already Exists with this Course code.' => '',
    'Course Code' => '',
    'Course ID' => '',
    'Course Management' => '',
    'Course Name' => '',
    'Create' => '',
    'Create New' => '',
    'Create Section' => '',
    'Created At' => '',
    'Created By' => '',
    'Delete' => '',
    'EXCEL' => '',
    'Edit Batch Details' => '',
    'Edit Course Details' => '',
    'Edit Section Details' => '',
    'End Date' => '',
    'Inactive' => '',
    'Initial Batch' => '',
    'Initial Section' => '',
    'Intake' => '',
    'Manage Batches' => '',
    'Manage Course' => '',
    'Manage Course Modules' => '',
    'Manage Courses' => '',
    'Manage Current Active Course' => '',
    'Manage Section' => '',
    'Manage Sections' => '',
    'No results found.' => '',
    'PDF' => '',
    'Section' => '',
    'Section Already Exists of this Batch.' => '',
    'Section Batch' => '',
    'Section ID' => '',
    'Section Name' => '',
    'Start Date' => '',
    'Status' => '',
    'Students' => '',
    'Update' => '',
    'Update Batch' => '',
    'Update Batches: ' => '',
    'Update Course' => '',
    'Update Courses: ' => '',
    'Update Section' => '',
    'Update Section: ' => '',
    'Updated At' => '',
    'Updated By' => '',
    'View Batch' => '',
    'View Batch Details' => '',
    'View Course' => '',
    'View Course Details' => '',
    'View Section' => '',
    'View Section Details' => '',
];
