<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '--- Select Type ---' => '',
    'ADD' => '',
    'Active' => '',
    'Add Event' => '',
    'Add Message of Day' => '',
    'Add Notice' => '',
    'All Day' => '',
    'Are you sure you want to delete this item?' => '',
    'Back' => '',
    'Cancel' => '',
    'Create' => '',
    'Create Events' => '',
    'Create New' => '',
    'Created At' => '',
    'Created By' => '',
    'Dashboard' => '',
    'Dashboard Modules' => '',
    'Date' => '',
    'Deactive' => '',
    'Delete' => '',
    'Description' => '',
    'Detail' => '',
    'Details' => '',
    'EXCEL' => '',
    'Employee' => '',
    'End Date' => '',
    'Enter Description' => '',
    'Enter Message Details' => '',
    'Enter Title' => '',
    'Event ID' => '',
    'Event Schedule' => '',
    'Event Type' => '',
    'Events' => '',
    'General' => '',
    'Holiday' => '',
    'Important Notice' => '',
    'Is Status' => '',
    'Manage Event Schedule' => '',
    'Manage Events' => '',
    'Manage Student/Employee Dashboard Notice' => '',
    'Manage Users Dashboard' => '',
    'Massage Of The Day' => '',
    'Meeting' => '',
    'Message of Day List' => '',
    'Messages' => '',
    'Msg Of Day ID' => '',
    'Notice' => '',
    'Notice File' => '',
    'Notice ID' => '',
    'Notice List' => '',
    'PDF' => '',
    'Remove' => '',
    'Remove/Delete Event' => '',
    'Select Date' => '',
    'Start Date' => '',
    'Status' => '',
    'Student' => '',
    'Title' => '',
    'Update' => '',
    'Update Event' => '',
    'Update Events: ' => '',
    'Update Message of Day' => '',
    'Update Message of Day: ' => '',
    'Update Notice' => '',
    'Update Notice: ' => '',
    'Updated At' => '',
    'Updated By' => '',
    'Url' => '',
    'User Type' => '',
    'View Message of Days' => '',
    'View Notice' => '',
];
