<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '--- Select Department ---' => '',
    '--- Select Designation ---' => '',
    'Active Employee' => '',
    'Active Students' => '',
    'Address' => '',
    'Admission Date' => '',
    'Attendence Card' => '',
    'Back' => '',
    'Bank Account No' => '',
    'Batch' => '',
    'Batch Name' => '',
    'Birth Date' => '',
    'Birth Place' => '',
    'Blood' => '',
    'Blood Group' => '',
    'Category' => '',
    'Category Name' => '',
    'Category Wise Student' => '',
    'Check All' => '',
    'City' => '',
    'Course' => '',
    'Course Wise Student Status' => '',
    'Date' => '',
    'Deactive Employee' => '',
    'Deactive Students' => '',
    'Department' => '',
    'Department Wise Joining Average' => '',
    'Designation' => '',
    'Email ID' => '',
    'Email Id' => '',
    'Email-ID' => '',
    'Employee Info Report' => '',
    'Employee List' => '',
    'Employee No' => '',
    'Excel' => '',
    'First Name' => '',
    'Gender' => '',
    'Gender Wise Employee' => '',
    'Gender Wise Student' => '',
    'Generate' => '',
    'Group' => '',
    'Guardian' => '',
    'Guardian Mobile' => '',
    'Guardian No' => '',
    'International' => '',
    'International Address' => '',
    'Joining' => '',
    'Joining Date' => '',
    'Languages Known' => '',
    'Last Name' => '',
    'Local' => '',
    'Local Address' => '',
    'Login History' => '',
    'Marital Status' => '',
    'Middle Name' => '',
    'Mobile No' => '',
    'More Info' => '',
    'Mother Name' => '',
    'No' => '',
    'No Record Found For This Criteria.' => '',
    'No Record To Display' => '',
    'Not Set' => '',
    'PDF' => '',
    'Please select atleast one checkbox' => '',
    'Reference' => '',
    'Religion' => '',
    'Report Center' => '',
    'Reports' => '',
    'SI No.' => '',
    'Section' => '',
    'Section Name' => '',
    'Select Criteria' => '',
    'Sr.No' => '',
    'Student Count' => '',
    'Student Info Report' => '',
    'Student No' => '',
    'Student Report' => '',
    'Students List' => '',
    'Total Employee' => '',
    'Year Wise Joining Employees' => '',
    'Reports Center' => '@@@@',
];
