<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '--- Select Course ---' => 'اختر الفرقة الدراسية',
    'ADD' => 'أضف',
    'Active' => 'نشط',
    'Add' => 'أضف',
    'Add Batch' => 'أضف عام دراسي',
    'Add Course' => 'أضف مقرر',
    'Add Section' => 'أضف مجموعة',
    'Are you sure you want to delete this item?' => 'هل ترغب في حذف هذه الفرقة الدراسية بالفعل؟',
    'Back' => 'عودة',
    'Batch' => 'العام الدراسي',
    'Batch Alias' => 'الاسم المختصر للعام الدراسي',
    'Batch Course' => 'مقرر العام الدراسي',
    'Batch ID' => 'كود العام الدراسي',
    'Batch Name' => 'اسم العام الدراسي',
    'Batches' => 'الدفعات',
    'Cancel' => 'إلغاء',
    'Course' => 'الفرقة',
    'Course Alias' => 'مختصر اسم الفرقة الدراسية',
    'Course Already Exists with this Course code.' => 'الفرقة الدراسية بموجودة بالفعل مع هذا الكود',
    'Course Code' => 'كود الفرقة الدراسية',
    'Course ID' => 'كود الفرقة الدراسية',
    'Course Management' => 'إدارة الفرقة الدراسية',
    'Course Name' => 'اسم الفرقة الدراسية',
    'Create' => 'انشاء',
    'Create New' => 'جديد',
    'Create Section' => 'انشيء مجموعة',
    'Created At' => 'انشئت في',
    'Created By' => 'بمعرفة',
    'Delete' => 'حذف',
    'EXCEL' => 'EXCEL',
    'Edit Batch Details' => 'تحرير تفاصيل العام الدراسي',
    'Edit Course Details' => 'تحرير تفاصيل الفرقة الدراسية',
    'Edit Section Details' => 'تحرير تفاصيل التخصص',
    'End Date' => 'تاريخ الانتهاء',
    'Inactive' => 'غير نشط',
    'Initial Batch' => 'العام الدراسي الأولى',
    'Initial Section' => 'التخصص الأولى',
    'Intake' => 'العدد',
    'Manage Batches' => 'إدارة الدفعات',
    'Manage Course' => 'إدارة الفرقة الدراسية',
    'Manage Course Modules' => 'إدارة موديولات الفرقة الدراسية',
    'Manage Courses' => 'إدارة الفرق الدراسية',
    'Manage Current Active Course' => 'إدارة الفرق الدراسية النشطة',
    'Manage Section' => 'إدارة التخصص',
    'Manage Sections' => 'إدارة التخصصات',
    'No results found.' => 'لم يتم العثور على نتائج',
    'PDF' => 'PDF',
    'Section' => 'التخصص',
    'Section Already Exists of this Batch.' => 'التخصص موجودة بالفعل في هذه العام الدراسي',
    'Section Batch' => 'عام دراسي التخصص',
    'Section ID' => 'كود التخصص',
    'Section Name' => 'اسم التخصص',
    'Start Date' => 'تاريخ الالتحاق',
    'Status' => 'الحالة',
    'Students' => 'الطلبة',
    'Update' => 'تحديث',
    'Update Batch' => 'تحديث العام الدراسي',
    'Update Batches: ' => 'تحديث الدفعات',
    'Update Course' => 'تحديث الفرقة الدراسية',
    'Update Courses: ' => 'تحديث الفرقة الدراسيةات',
    'Update Section' => 'تحديث التخصص',
    'Update Section: ' => 'تحديث التخصص',
    'Updated At' => 'تم التحديث في',
    'Updated By' => 'بمعرفة',
    'View Batch' => 'اظهار العام الدراسي',
    'View Batch Details' => 'اظهار تفاصيل العام الدراسي',
    'View Course' => 'اظهار الفرقة الدراسية',
    'View Course Details' => 'إظهار تفاصيل الفرقة الدراسية',
    'View Section' => 'إظهار التخصص',
    'View Section Details' => 'إظهار تفاصيل التخصص',
];
