<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '--- Select Type ---' => 'اختر النوع',
    'ADD' => 'أضف',
    'Active' => 'نشط',
    'Add Event' => 'أضف فعالية',
    'Add Message of Day' => 'أضف رسالة اليوم',
    'Add Notice' => 'أضف ملحوظة',
    'All Day' => 'كل الأيام',
    'Are you sure you want to delete this item?' => 'هل أنتَ متأكد من أنك ترغب في حذف هذا بالفعل؟',
    'Back' => 'عودة',
    'Cancel' => 'إلغاء',
    'Create' => 'إنشاء',
    'Create Events' => 'إنشاء فعالية',
    'Create New' => 'أضف جديد',
    'Created At' => 'تاريخ الانشاء',
    'Created By' => 'انشيء بمعرفة',
    'Dashboard' => 'الرئيسية',
    'Dashboard Modules' => 'مودولات الصفحة الرئيسية',
    'Date' => 'التاريخ',
    'Deactive' => 'غير نشط',
    'Delete' => 'حذف',
    'Description' => 'وصف',
    'Detail' => 'التفاصيل',
    'Details' => 'التفاصيل',
    'EXCEL' => 'EXCEL',
    'Employee' => 'الموظف',
    'End Date' => 'تاريخ الانتهاء',
    'Enter Description' => 'ادخل التفاصيل',
    'Enter Message Details' => 'ادخ تفاصيل الرسالة',
    'Enter Title' => 'اكتب العنوان',
    'Event ID' => 'كود الفعالية',
    'Event Schedule' => 'موعد الفعالية',
    'Event Type' => 'نوع الفعالية',
    'Events' => 'الفعاليات',
    'General' => 'عام',
    'Holiday' => 'إجازة',
    'Important Notice' => 'ملحوظة هامة',
    'Is Status' => 'حالة الطالب',
    'Manage Event Schedule' => 'ضبط موعد الفعالية',
    'Manage Events' => 'ضبط الفعاليات',
    'Manage Student/Employee Dashboard Notice' => 'ضبط الملاحظات على صفحة الطالب / الموظف',
    'Manage Users Dashboard' => 'ضبط صفحة المستخدم',
    'Massage Of The Day' => 'حكمة اليوم',
    'Meeting' => 'اللقاءات',
    'Message of Day List' => 'قائمة حكم اليوم',
    'Messages' => 'الرسائل',
    'Msg Of Day ID' => 'كود حكمة اليوم',
    'Notice' => 'ملحوظة',
    'Notice File' => 'ملف الملحوظة',
    'Notice ID' => 'كود الملحوظة',
    'Notice List' => 'قائمة الملحوظات',
    'PDF' => 'PDF',
    'Remove' => 'حذف',
    'Remove/Delete Event' => 'حذف الفعالية',
    'Select Date' => 'اختر التاريخ',
    'Start Date' => 'اختر اليوم',
    'Status' => 'الحالة',
    'Student' => 'الطالب',
    'Title' => 'اسم الفعالية',
    'Update' => 'تحديث',
    'Update Event' => 'تحديث الفعالية',
    'Update Events: ' => 'تحديث الفعاليات',
    'Update Message of Day' => 'تحديث حكمة اليوم',
    'Update Message of Day: ' => 'تحديث حكمة اليوم',
    'Update Notice' => 'تحديث الملحوظات',
    'Update Notice: ' => 'تحديث الملحوظات',
    'Updated At' => 'تم التحديث في',
    'Updated By' => 'بمعرفة',
    'Url' => '',
    'User Type' => 'نوع المستخدم',
    'View Message of Days' => 'إظهار حكمة اليوم',
    'View Notice' => 'إظهار الملحوظة',
];
