<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Reports Center' => '@@@@',
    '--- Select Department ---' => 'اختر القسم',
    '--- Select Designation ---' => 'الدرجة الوظيفية',
    'Active Employee' => 'موظف نشط',
    'Active Students' => 'طلبة نشطون',
    'Address' => 'العنوان',
    'Admission Date' => 'تاريخ القبول',
    'Attendence Card' => 'بطاقة الحضور',
    'Back' => 'عودة',
    'Bank Account No' => 'رقم حساب البنك',
    'Batch' => 'الدفعة',
    'Batch Name' => 'اسم الدفعة',
    'Birth Date' => 'تاريخ الميلاد',
    'Birth Place' => 'محل الميلاد',
    'Blood' => 'الدم',
    'Blood Group' => 'فصيلة الدم',
    'Category' => 'الفئة',
    'Category Name' => 'اسم الفئة',
    'Category Wise Student' => 'فئة الطالب',
    'Check All' => 'اختر الكل',
    'City' => 'المدينة',
    'Course' => 'المادة',
    'Course Wise Student Status' => 'حالة الطالب',
    'Date' => 'التاريخ',
    'Deactive Employee' => 'إيقاف الموظف',
    'Deactive Students' => 'إيقاف الطلبة',
    'Department' => 'القسم',
    'Department Wise Joining Average' => 'متوسط الالتحاق بالأقسام',
    'Designation' => 'الدرجة الوظيفية',
    'Email ID' => 'كود الميل',
    'Email Id' => 'كود الميل',
    'Email-ID' => 'كود الميل',
    'Employee Info Report' => 'تقرير عن الموظف',
    'Employee List' => 'قائمة الموظفين',
    'Employee No' => 'رقم الموظف',
    'Excel' => 'Excel',
    'First Name' => 'الاسم الأول',
    'Gender' => 'النوغ',
    'Gender Wise Employee' => 'تقرير عن نوع المدرسين',
    'Gender Wise Student' => 'نوع الطلبة',
    'Generate' => 'إنشاء',
    'Group' => 'المجموعة',
    'Guardian' => 'الوالدان',
    'Guardian Mobile' => 'هاتف الوالدين',
    'Guardian No' => 'رقم الوالدين',
    'International' => 'الدولي',
    'International Address' => 'العنوان الدولي',
    'Joining' => 'الالتحاق',
    'Joining Date' => 'تاريخ الالتحاق',
    'Languages Known' => 'اللغات',
    'Last Name' => 'الاسم الأخير',
    'Local' => 'بينات داخل الدولة',
    'Local Address' => 'العنوان المحلي',
    'Login History' => 'تاريخ الدخول الى الموقع',
    'Marital Status' => 'الحالة الاجتماعية',
    'Middle Name' => 'اسم الأب',
    'Mobile No' => 'رقم الهاتف',
    'More Info' => 'المزيد',
    'Mother Name' => 'اسم الام',
    'No' => 'رقم',
    'No Record Found For This Criteria.' => 'لا توجد بيانات مسجلة لهذه الفئة',
    'No Record To Display' => 'لا توجد بيانات للعرض',
    'Not Set' => 'غير مُعد',
    'PDF' => 'PDF',
    'Please select atleast one checkbox' => 'اختر واحد على الأقل',
    'Reference' => 'المرجعية',
    'Religion' => 'الديانة',
    'Report Center' => 'التقارير',
    'Reports' => 'التقارير',
    'SI No.' => 'الرقم المسلسل',
    'Section' => 'القسم',
    'Section Name' => 'اسم القسم',
    'Select Criteria' => 'اختر المتطلبات',
    'Sr.No' => 'ر. مسلسل',
    'Student Count' => 'عدد الطلبة',
    'Student Info Report' => 'تقرير عن الطالب',
    'Student No' => 'رقم الطالب',
    'Student Report' => 'تقرير عن الطالب',
    'Students List' => 'قائمة الطلبة',
    'Total Employee' => 'إجمالي عدد الطلبة',
    'Year Wise Joining Employees' => 'التحاق المدرسين خلال العام',
];
