<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Course Already Exists with this Course code.' => 'કોર્સ પહેલેથી જ આ કોર્સ કોડ સાથે અસ્તિત્વમાં છે.',
    'Section Already Exists of this Batch.' => 'વિભાગ પહેલેથી જ આ બેચ સાથે અસ્તિત્વમાં છે.',
    '--- Select Course ---' => '--- અભ્યાસક્રમ પસંદ કરો ---',
    'ADD' => 'ઉમેરો',
    'Active' => 'સક્રિય',
    'Add' => 'ઉમેરો',
    'Add Batch' => 'બેચ ઉમેરો',
    'Add Course' => 'અભ્યાસક્રમ ઉમેરો',
    'Add Section' => 'વિભાગ ઉમેરો',
    'Are you sure you want to delete this item?' => 'તમે આ રેકોર્ડ કાઢી નાખવા માંગો છો તમને ખાતરી છે?',
    'Back' => 'પાછળ જાઓ',
    'Batch' => 'બૅચ',
    'Batch Alias' => 'બેચનું ઉપનામ',
    'Batch Course' => 'બેચ માટે અભ્યાસક્રમ',
    'Batch ID' => 'બેચનું આઈડી',
    'Batch Name' => 'બેચનું નામ',
    'Batches' => 'બૅચીસ',
    'Cancel' => 'રદ કરો',
    'Course' => 'અભ્યાસક્રમ',
    'Course Alias' => 'અભ્યાસક્રમનું ઉપનામ ',
    'Course Code' => 'અભ્યાસક્રમનો કોડ',
    'Course ID' => 'અભ્યાસક્રમનું આઈડી',
    'Course Management' => 'અભ્યાસક્રમનું સંચાલન',
    'Course Name' => 'અભ્યાસક્રમનું નામ',
    'Create' => 'નવું ઉમેરો',
    'Create New' => 'નવું ઉમેરો',
    'Create Section' => 'વિભાગ ઉમેરો',
    'Created At' => 'બનાવતી વખતનો સમય',
    'Created By' => 'બનાવનાર યુઝર',
    'Delete' => 'દૂર કરો',
    'EXCEL' => 'એક્સેલ',
    'Edit Batch Details' => 'બેચની વિગતોમા ફેરફાર કરો',
    'Edit Course Details' => 'અભ્યાસક્રમની વિગતોમા ફેરફાર કરો',
    'Edit Section Details' => 'વિભાગની વિગતોમા ફેરફાર કરો',
    'End Date' => 'સમાપ્તિની તારીખ',
    'Inactive' => 'નિષ્ક્રિય',
    'Initial Batch' => 'પ્રારંભિક બેચ',
    'Initial Section' => 'પ્રારંભિક વિભાગ',
    'Intake' => 'ક્ષમતા',
    'Manage Batches' => 'બૅચીસ મેનેજ કરો',
    'Manage Course' => 'અભ્યાસક્રમ મેનેજ કરો',
    'Manage Course Modules' => 'અભ્યાસક્રમના મોડ્યુલ્સ મેનેજ કરો',
    'Manage Courses' => 'અભ્યાસક્રમો મેનેજ કરો',
    'Manage Current Active Course' => 'વર્તમાન સક્રિય અભ્યાસક્રમ મેનેજ કરો',
    'Manage Section' => 'વિભાગ મેનેજ કરો',
    'Manage Sections' => 'વિભાગો મેનેજ કરો',
    'No results found.' => 'કોઈ પરિણામ મળ્યા નથી.',
    'PDF' => 'પીડીએફ',
    'Section' => 'વિભાગ',
    'Section Batch' => 'વિભાગ માટે બેચ',
    'Section ID' => 'વિભાગનું આઈડી',
    'Section Name' => 'વિભાગનું નામ',
    'Start Date' => 'શરૂઆતની તારીખ',
    'Status' => 'સ્થિતિ',
    'Students' => 'વિદ્યાર્થીઓ',
    'Update' => 'અપડેટ',
    'Update Batch' => 'બેચ અપડેટ કરો',
    'Update Batches: ' => 'બૅચીસ અપડેટ કરો',
    'Update Course' => 'અભ્યાસક્રમ અપડેટ કરો',
    'Update Courses: ' => 'અભ્યાસક્રમો અપડેટ કરો',
    'Update Section' => 'વિભાગ અપડેટ કરો',
    'Update Section: ' => 'વિભાગો અપડેટ કરો',
    'Updated At' => 'સુધારા વખતનો સમય',
    'Updated By' => 'સુધારાનાર',
    'View Batch' => 'જુઓ બેચ',
    'View Batch Details' => 'બેચની વિગતો જુઓ',
    'View Course' => 'જુઓ અભ્યાસક્રમ',
    'View Course Details' => 'અભ્યાસક્રમની વિગતો જુઓ',
    'View Section' => 'જુઓ વિભાગ',
    'View Section Details' => 'વિભાગની વિગતો જુઓ',
];
