<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add Event' => 'કાર્યક્રમ ઉમેરો',
    'Update Event' => 'કાર્યક્રમ અપડેટ કરો',
    'Url' => '',
    '--- Select Type ---' => '--- પ્રકાર પસંદ કરો ---',
    'ADD' => 'ઉમેરો',
    'Active' => 'સક્રિય',
    'Add Message of Day' => 'આજ નો સંદેશ ઉમેરો',
    'Add Notice' => 'નોટિસ ઉમેરો',
    'All Day' => 'બધા દિવસો',
    'Are you sure you want to delete this item?' => 'તમે આ રેકોર્ડ કાઢી નાખવા માંગો છો તમને ખાતરી છે?',
    'Back' => 'પાછળ જાઓ',
    'Cancel' => 'રદ કરો',
    'Create' => 'નવું ઉમેરો',
    'Create Events' => 'નવા કાર્યક્રમો ઉમેરો',
    'Create New' => 'નવું ઉમેરો',
    'Created At' => 'બનાવતી વખતનો સમય',
    'Created By' => 'બનાવનાર યુઝર',
    'Dashboard' => 'ડેશબોર્ડ',
    'Dashboard Modules' => 'ડેશબોર્ડના મોડ્યુલ્સ',
    'Date' => 'તારીખ',
    'Deactive' => 'નિષ્ક્રિય',
    'Delete' => 'દૂર કરો',
    'Description' => 'વિવરણ',
    'Detail' => 'વિગત',
    'Details' => 'વિગતો',
    'EXCEL' => 'એક્સેલ',
    'Employee' => 'કર્મચારી',
    'End Date' => 'સમાપ્તિની તારીખ',
    'Enter Description' => 'ડિસ્ક્રિપશન',
    'Enter Message Details' => 'સંદેશની વિગતો',
    'Enter Title' => 'શીર્ષક',
    'Event ID' => 'કાર્યક્રમનું આઈડી',
    'Event Schedule' => 'કાર્યક્રમનું શેડ્યૂલ',
    'Event Type' => 'કાર્યક્રમનો પ્રકાર',
    'Events' => 'કાર્યક્રમો',
    'General' => 'જનરલ',
    'Holiday' => 'રજાઓ',
    'Important Notice' => 'અગત્યની નોટીસ',
    'Is Status' => 'સ્થિતિ?',
    'Manage Event Schedule' => 'કાર્યક્રમનું શેડ્યૂલ મેનેજ કરો',
    'Manage Events' => 'કાર્યક્રમો મેનેજ કરો',
    'Manage Student/Employee Dashboard Notice' => 'વિદ્યાર્થી/કર્મચારીના ડેશબોર્ડની નોટિસ મેનેજ કરો',
    'Manage Users Dashboard' => 'યુઝૅસ ડેશબોર્ડ મેનેજ કરો',
    'Massage Of The Day' => 'આજનો સંદેશ',
    'Meeting' => 'મુલાકાત',
    'Message of Day List' => 'આજનો સંદેશની યાદી',
    'Messages' => 'સંદેશાઓ',
    'Msg Of Day ID' => 'આજનો સંદેશ',
    'Notice' => 'નોટીસ',
    'Notice File' => 'નોટીસ ફાઇલ',
    'Notice ID' => 'નોટીસનું આઈડી',
    'Notice List' => 'નોટીસની યાદી',
    'PDF' => 'પીડીએફ',
    'Remove' => 'કાઢી નાખો',
    'Remove/Delete Event' => 'કાર્યક્રમ કાઢી નાખો/દૂર કરો',
    'Select Date' => 'તારીખ પસંદ કરો',
    'Start Date' => 'શરૂઆતની તારીખ',
    'Status' => 'સ્થિતિ',
    'Student' => 'વિદ્યાર્થી',
    'Title' => 'શીર્ષક',
    'Update' => 'અપડેટ',
    'Update Events: ' => 'કાર્યક્રમો અપડેટ કરો',
    'Update Message of Day' => 'આજનો સંદેશ અપડેટ કરો',
    'Update Message of Day: ' => 'આજનો સંદેશ અપડેટ કરો:',
    'Update Notice' => 'નોટીસ અપડેટ કરો',
    'Update Notice: ' => 'નોટીસ અપડેટ કરો:',
    'Updated At' => 'સુધારા વખતનો સમય',
    'Updated By' => 'સુધારાનાર',
    'User Type' => 'યુઝરનો પ્રકાર',
    'View Message of Days' => 'આજનો સંદેશ જુઓ',
    'View Notice' => 'નોટીસ જુઓ',
];
