<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Student Report' => '',
    '--- Select Department ---' => ' --- વિભાગ પસંદ કરો ---',
    '--- Select Designation ---' => '--- હોદ્દો પસંદ કરો ---',
    'Active Employee' => 'સક્રિય કર્મચારીઓ',
    'Active Students' => 'સક્રિય વિદ્યાર્થીઓ',
    'Address' => 'સરનામું',
    'Admission Date' => 'એડમિશન તારીખ',
    'Attendence Card' => 'હાજરી પત્રક',
    'Back' => 'પાછળ જાઓ',
    'Bank Account No' => 'બૅન્ક ઍકાઉન્ટ નં.',
    'Batch' => 'બેચ',
    'Batch Name' => 'બેચનું નામ',
    'Birth Date' => 'જન્મ તારીખ',
    'Birth Place' => 'જન્મસ્થાન',
    'Blood' => 'બ્લડ',
    'Blood Group' => 'બ્લડ ગ્રુપ',
    'Category' => 'પ્રકાર',
    'Category Name' => 'પ્રકારનું નામ',
    'Category Wise Student' => 'અભ્યાસક્રમ મુજબ વિદ્યાર્થીઓ',
    'Check All' => 'બધા પસંદ કરો',
    'City' => 'શહેર',
    'Course' => 'અભ્યાસક્રમ',
    'Course Wise Student Status' => 'સ્થિતિ મુજબ અભ્યાસક્રમનાં વિદ્યાર્થીઓ',
    'Date' => 'તારીખ',
    'Deactive Employee' => 'નિષ્ક્રિય કર્મચારીઓ',
    'Deactive Students' => 'નિષ્ક્રિય વિદ્યાર્થીઓ',
    'Department' => 'વિભાગ',
    'Department Wise Joining Average' => 'વિભાગ મુજબ જોડાયેલ કર્મચારીઓની  સરેરાશ ',
    'Designation' => 'હોદ્દો',
    'Email ID' => 'ઇમેઇલ આઈડી',
    'Email Id' => 'ઇમેઇલ આઈડી',
    'Email-ID' => 'ઇમેઇલ-આઈડી',
    'Employee Info Report' => 'કર્મચારી માહિતી રિપોર્ટ',
    'Employee List' => 'કર્મચારીઓની યાદી',
    'Employee No' => 'કર્મચારી નં.',
    'Excel' => 'એક્સેલ',
    'First Name' => 'પહેલું નામ',
    'Gender' => 'જાતિ',
    'Gender Wise Employee' => 'જાતિ મુજબ કર્મચારીઓ',
    'Gender Wise Student' => 'જાતિ મુજબ વિદ્યાર્થીઓ',
    'Generate' => 'જનરેટ',
    'Group' => 'ગ્રુપ',
    'Guardian' => 'વાલીઓ',
    'Guardian Mobile' => 'વાલીનો મોબાઇલ નં.',
    'Guardian No' => 'વાલીનો મોબાઇલ નં.',
    'International' => 'આંતરરાષ્ટ્રીય',
    'International Address' => 'આંતરરાષ્ટ્રીય સરનામું',
    'Joining' => 'જોડાયા',
    'Joining Date' => 'જોડાયા તારીખ',
    'Languages Known' => 'ભાષાઓ જાણે છે',
    'Last Name' => 'લાસ્ટ નામ',
    'Local' => 'સ્થાનિક',
    'Local Address' => 'સ્થાનિક સરનામું',
    'Login History' => 'લૉગિનનો ઇતિહાસ',
    'Marital Status' => 'વૈવાહિક સ્થિતિ',
    'Middle Name' => 'મધ્ય નામ',
    'Mobile No' => 'મોબાઈલ નં.',
    'More Info' => 'વધારે માહિતી',
    'Mother Name' => 'માતાનું નામ',
    'No' => 'ના',
    'No Record Found For This Criteria.' => 'આ માપદંડ માટે કોઈ  રેકોર્ડ નથી.',
    'No Record To Display' => 'કોઈ રેકોર્ડ નથી.',
    'Not Set' => 'સેટ નથી',
    'PDF' => 'પીડીએફ',
    'Please select atleast one checkbox' => 'ઓછામાં ઓછા એક ચકાસણીબોક્સ પસંદ કરો',
    'Reference' => 'રેફરન્સ',
    'Religion' => 'ધર્મ',
    'Report Center' => 'રિપોર્ટ સેન્ટર',
    'Reports' => 'રિપોર્ટ્સ',
    'SI No.' => 'સીરીયલ નં.',
    'Section' => 'વિભાગ',
    'Section Name' => 'વિભાગનું નામ',
    'Select Criteria' => 'ક્રાઇટેરિયા પસંદ કરો',
    'Sr.No' => 'સીરીયલ નં.',
    'Student Count' => 'વિદ્યાર્થી કાઉન્ટ',
    'Student Info Report' => 'વિદ્યાર્થી માહિતી રિપોર્ટ',
    'Student No' => 'વિદ્યાર્થી નં.',
    'Students List' => 'વિદ્યાર્થીઓની યાદી',
    'Total Employee' => 'કુલ કર્મચારીઓ',
    'Year Wise Joining Employees' => 'વર્ષ મુજબ જોડાયેલા કર્મચારીઓ',
];
